<a href="https://colab.research.google.com/github/Camper-Lingo/CP1_SERS/blob/main/CP1_SERS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Dataset 1 — Appliances Energy Prediction  (UCI)**

Fonte: https://archive.ics.uci.edu/dataset/374/appliances+energy+prediction

**Situação**

Uma empresa de eficiência energética está analisando o comportamento de uma residência de baixo consumo. A equipe deseja identificar períodos de consumo elevado dos eletrodomésticos e observar quais condições de temperatura e umidade estavam presentes nesses momentos.

![untitled.svg]()

In [62]:
import pandas as pd

In [63]:
df1 = pd.read_csv('/content/energydata_SAMPLE.csv')

In [64]:
df1.head()

   Appliances  lights       T1     RH_1       T2     RH_2       T3     RH_3
0          40       0  20.8900  35.4000  17.7600  39.1633  20.2900  36.9000
1          90      10  21.8900  53.1000  21.2900  45.3600  21.6333  49.2267
2          50       0  21.3900  35.5000  17.6333  40.5300  21.6667  35.2000
3          50       0  21.3900  41.0333  23.8900  34.8400  22.0333  36.9333
4          70       0  19.9633  35.1267  16.4633  40.1267  20.0000  36.4000

In [65]:
df1.shape

(1974, 8)

In [66]:
print(f'Número de linhas: {df1.shape[0]}')
print(f'Número de colunas: {df1.shape[1]}')

Número de linhas: 1974
Número de colunas: 8

In [67]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1974 entries, 0 to 1973
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Appliances  1974 non-null   int64
 1   lights      1974 non-null   int64
 2   T1          1974 non-null   float64
 3   RH_1        1974 non-null   float64
 4   T2          1974 non-null   float64
 5   RH_2        1974 non-null   float64
 6   T3          1974 non-null   float64
 7   RH_3        1974 non-null   float64
dtypes: float64(6), int64(2)
memory usage: 123.5 KB

In [68]:
df1.describe()

,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3
count,1974.000000,1974.000000,1974.000000,1974.000000,1974.000000,1974.000000,1974.000000,1974.000000
mean,93.044580,3.839919,21.664703,40.219193,20.293635,40.411386,22.231615,39.209733
std,93.826149,7.937076,1.574883,3.971923,2.126958,4.037686,1.957275,3.288818
min,20.000000,0.000000,16.790000,27.733300,16.100000,24.063300,17.200000,30.133300
25%,50.000000,0.000000,20.700000,37.205825,18.790000,37.760000,20.700000,36.900000
50%,60.000000,0.000000,21.600000,39.590000,20.000000,40.433300,22.100000,38.433300
75%,100.000000,0.000000,22.600000,42.991675,21.500000,43.228325,23.290000,41.741250
max,770.000000,50.000000,26.260000,57.496700,28.917500,56.026700,29.198600,49.226700

In [69]:
df1.columns

Index(['Appliances', 'lights', 'T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3'], dtype='object')

In [70]:
# 2.	Renomeie Appliances para Consumo_Eletrodomesticos e simplifique
#  o nome de pelo menos três atributos ambientais.
df1.rename(columns={'Appliances': 'Consumo_Eletrodomesticos',
                    'T1': 'Temperatura_01',
                    'RH_1': 'Umidade_01'}, inplace=True)

In [71]:
df1.head()

,Consumo_Eletrodomesticos,lights,Temperatura_01,Umidade_01,T2,RH_2,T3,RH_3
0,40,0,20.8900,35.4000,17.7600,39.1633,20.2900,36.9000
1,90,10,21.8900,53.1000,21.2900,45.3600,21.6333,49.2267
2,50,0,21.3900,35.5000,17.6333,40.5300,21.6667,35.2000
3,50,0,21.3900,41.0333,23.8900,34.8400,22.0333,36.9333
4,70,0,19.9633,35.1267,16.4633,40.1267,20.0000,36.4000

#DataSet 2 - Steel Industry Energy Consumption (UCI)

In [72]:
import pandas as pd

dados = pd.read_csv("amostra_dataset2_steel.csv")

dados.head()

FileNotFoundError: [Errno 2] No such file or directory: 'amostra_dataset2_steel.csv'

In [ ]:
dados = dados.rename(columns={
    "Usage_kWh": "Consumo_kWh",
    "Lagging_Current_Power_Factor": "FP_Atraso",
    "Leading_Current_Power_Factor": "FP_Avanco"
})

dados.head()

In [ ]:
print(dados.shape)
dados.info()
dados.describe()

# Dataset 3 — Power Consumption of Tetouan City (UCI)

Fonte: https://archive.ics.uci.edu/dataset/849/power+consumption+of+tetouan+city

Situação:

Uma equipe responsável pelo planejamento da distribuição de energia em Tétouan deseja identificar qual das três zonas apresenta o maior pico de consumo e observar as condições ambientais registradas nos momentos de maior demanda

In [73]:
df3 = pd.read_csv('/content/Tetuan City power consumption.csv')

In [74]:
df3.columns

Index(['Temperature', 'Humidity', 'Wind Speed'], dtype='object')

In [75]:
#Renomeie as três variáveis de consumo para Consumo_Zona_1, Consumo_Zona_2 e Consumo_Zona_3

df3 = df3.rename(columns={
    'Temperature': 'Consumo_Zona_1',
    'Humidity': 'Consumo_Zona_2',
    'Wind Speed': 'Consumo_Zona_3'
})

In [76]:
#Determine o consumo máximo registrado em cada uma das três zonas.

df3['Consumo_Zona_1'] = pd.to_numeric(df3['Consumo_Zona_1'], errors='coerce')
df3['Consumo_Zona_2'] = pd.to_numeric(df3['Consumo_Zona_2'], errors='coerce')
df3['Consumo_Zona_3'] = pd.to_numeric(df3['Consumo_Zona_3'], errors='coerce')


maximos = df3[['Consumo_Zona_1', 'Consumo_Zona_2', 'Consumo_Zona_3']].max()
print(maximos)
#Identifique qual zona apresenta o maior pico de consumo na amostra.
zona_maior_pico = maximos.idxmax()
maior_pico = maximos.max()

print("Zona com maior pico:", zona_maior_pico)
print("Valor do maior pico:", maior_pico)
#Para a zona identificada, calcule 70% do valor máximo e crie um DataFrame com os registros acima desse limiar.
valor_maximo = df3[zona_maior_pico].max()
limiar = 0.70 * valor_maximo
df_acima_limiar = df3[df3[zona_maior_pico] > limiar]

print("Limiar (70%):", limiar)
print(df_acima_limiar)

Consumo_Zona_1    39.600
Consumo_Zona_2    94.700
Consumo_Zona_3     4.998
dtype: float64
Zona com maior pico: Consumo_Zona_2
Valor do maior pico: 94.7
Limiar (70%): 66.28999999999999
      Consumo_Zona_1  Consumo_Zona_2  Consumo_Zona_3
5              12.42           72.30           0.081
6              14.58           80.60           0.080
7              14.99           69.14           0.074
8              11.16           70.80           0.080
9              19.21           89.40           4.923
...              ...             ...             ...
5236           16.34           82.30           0.069
5237           17.20           80.10           4.909
5240           16.93           76.10           0.082
5241           10.93           67.88           0.082
5243           16.99           83.00           0.081

[3095 rows x 3 columns]

In [77]:
#Conte os registros e calcule o percentual que eles representam.

# Conta os registros acima do limiar
quantidade = len(df_acima_limiar)

# Calcula o percentual em relação ao total da amostra
percentual = (quantidade / len(df3)) * 100

print("Quantidade de registros:", quantidade)
print("Percentual:", percentual, "%")

Quantidade de registros: 3095
Percentual: 59.019832189168575 %

In [78]:
#Calcule a temperatura média e crie um segundo DataFrame contendo consumo acima do limiar e temperatura acima da média.

# Calcula a temperatura média
temperatura_media = df3['Consumo_Zona_1'].mean()

# Cria o DataFrame com as duas condições
df_acima_limiar_temperatura = df3[
    (df3[zona_maior_pico] > limiar) &
    (df3['Consumo_Zona_1'] > temperatura_media)
]

print("Temperatura média:", temperatura_media)
print(df_acima_limiar_temperatura)

Temperatura média: 18.855991606257156
      Consumo_Zona_1  Consumo_Zona_2  Consumo_Zona_3
9              19.21           89.40           4.923
14             21.03           86.50           0.068
27             26.92           70.20           4.909
29             25.37           77.80           4.918
31             24.60           91.30           4.918
...              ...             ...             ...
5215           26.22           82.50           4.916
5228           25.35           82.30           4.914
5230           18.88           87.60           4.917
5233           26.36           76.30           4.920
5235           21.89           68.49           4.913

[1251 rows x 3 columns]

In [79]:
#Compare os dois conjuntos e explique o que ocorreu com a quantidade de registros após a inclusão da condição ambiental.

# Quantidade antes da condição de temperatura
qtd_antes = len(df_acima_limiar)

# Quantidade depois de adicionar a condição de temperatura
qtd_depois = len(df_acima_limiar_temperatura)

# Diferença
diferenca = qtd_antes - qtd_depois

# Percentual de redução
percentual_reducao = (diferenca / qtd_antes) * 100

print("Registros antes:", qtd_antes)
print("Registros depois:", qtd_depois)
print("Registros removidos:", diferenca)
print(f"Redução: {percentual_reducao:.2f}%")

Registros antes: 3095
Registros depois: 1251
Registros removidos: 1844
Redução: 59.58%

#Dataset 5 — Wind & Solar Energy Production (Kaggle)

In [87]:
df5 = pd.read_csv('/content/Energy Production Dataset.csv')

In [88]:
df5 = df5.pivot_table(
    index=['Date', 'Start_Hour', 'End_Hour', 'Day_of_Year', 'Season', 'Month_Name'],
    columns='Source',
    values='Production',
    fill_value=0
).reset_index()

In [89]:
df5.rename(columns={
    'Solar': 'Geracao_Solar',
    'Wind': 'Geracao_Eolica',
                    }, inplace=True)

In [90]:
df5.head()

Source,Date,Start_Hour,End_Hour,Day_of_Year,Season,Month_Name,Geracao_Solar,Geracao_Eolica
0,1/1/2020,15,16,1,Winter,January,0.0,1323.0
1,1/1/2020,19,20,1,Winter,January,0.0,1181.0
2,1/1/2021,4,5,1,Winter,January,0.0,998.0
3,1/1/2021,12,13,1,Winter,January,1994.0,0.0
4,1/1/2021,19,20,1,Winter,January,0.0,1425.0

In [91]:
max_solar = df5['Geracao_Solar'].max()

In [92]:
max_eolica = df5['Geracao_Eolica'].max()

In [93]:
limiar = 0.70
limite_solar = limiar * max_solar
limite_eolica = limiar * max_eolica

In [94]:
df_alta_solar = df5[df5['Geracao_Solar'] >= limite_solar].copy()

In [95]:
df_alta_eolica = df5[df5['Geracao_Eolica'] >= limite_eolica].copy()

In [96]:
total_registros = len(df5)
qtd_alta_solar = len(df_alta_solar)
qtd_alta_eolica = len(df_alta_eolica)
pct_alta_solar = (qtd_alta_solar / total_registros) * 100
pct_alta_eolica = (qtd_alta_eolica / total_registros) * 100

In [97]:
print(f"Total de registros na base: {total_registros:,}")
print("-" * 45)
print(f"Alta Geração Solar  : {qtd_alta_solar:,} registros ({pct_alta_solar:.2f}%)")
print(f"Alta Geração Eólica : {qtd_alta_eolica:,} registros ({pct_alta_eolica:.2f}%)")

Total de registros na base: 10,373
---------------------------------------------
Alta Geração Solar  : 45 registros (0.43%)
Alta Geração Eólica : 245 registros (2.36%)

In [98]:
if pct_alta_solar > pct_alta_eolica:
    diferenca = pct_alta_solar - pct_alta_eolica
    print(f"A fonte SOLAR opera com maior frequência acima de 70% do seu pico "
          f"({pct_alta_solar:.2f}% vs {pct_alta_eolica:.2f}% eólica, diferença de +{diferenca:.2f} p.p.).")
elif pct_alta_eolica > pct_alta_solar:
    diferenca = pct_alta_eolica - pct_alta_solar
    print(f"A fonte EÓLICA opera com maior frequência acima de 70% do seu pico "
          f"({pct_alta_eolica:.2f}% vs {pct_alta_solar:.2f}% solar, diferença de +{diferenca:.2f} p.p.).")
else:
    print(f"Ambas as fontes apresentaram a mesma frequência de operação acima de 70% "
          f"({pct_alta_solar:.2f}%).")

A fonte EÓLICA opera com maior frequência acima de 70% do seu pico (2.36% vs 0.43% solar, diferença de +1.93 p.p.).

Como as usinas solares e eólicas possuem capacidades instaladas e escalas distintas, comparar sua produção por valores fixos em megawatts distorce a análise em favor da fonte de maior porte.     Este codigo esta condisente com oq foi pedido na atividade

#Dataset 6 — Individual Household Electric Power Consumption (UCI)
Fonte: https://archive.ics.uci.edu/dataset/235/individual+household+electric+power+consumption

Situação:

Uma residência possui monitoramento elétrico detalhado e deseja identificar episódios de demanda elevada que também apresentem corrente acima do comportamento médio. O dataset é o mesmo utilizado como referência em aula, mas o critério de análise será diferente.

In [99]:
df6 = pd.read_csv("/content/energydata_SAMPLE.csv")

In [100]:
df6.columns

Index(['Appliances', 'lights', 'T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3'], dtype='object')

In [101]:
#Carregue a nova amostra e organize os atributos utilizando nomes mais simples.

df6 = df6.rename(columns={
    'Appliances': 'eletrodomesticos',
    'lights': 'luzes',
    'T1': 'temp1',
    'T2': 'temp2',
    'T3':'temp3',
    'RH_1':'unidade1',
    'RH_2': 'unidade2',
    'RH_3': 'unidade3'

})

In [102]:
#Determine o valor máximo de potência ativa.
df6["eletrodomesticos"].max()

770

In [106]:
#Calcule 75% do valor máximo e crie um DataFrame contendo registros acima desse limite.

valor_maximo = df6["eletrodomesticos"].max()

limite = 0.75 * valor_maximo

df_acima_limite = df6[df6["eletrodomesticos"] > limite]

print("Valor máximo:", valor_maximo)
print("Limite de 75%:", limite)
print(df_acima_limite)

Valor máximo: 770
Limite de 75%: 577.5
      eletrodomesticos  luzes    temp1  unidade1    temp2  unidade2    temp3  \
352                620      0  24.3900   44.3333  25.3700   37.7360  26.7300
427                650      0  20.8900   36.7000  18.2900   39.6633  21.2000
696                590     30  19.8567   47.6633  18.7000   34.1000  18.4267
744                740     20  19.5000   42.1333  18.2600   39.1967  19.8900
916                750     30  22.4300   43.0000  21.9267   40.1333  21.2300
993                690     10  22.5333   45.0267  22.0667   39.7900  22.3900
1173               580      0  21.6000   34.6267  19.5000   33.7600  22.5750
1182               600     20  24.8900   48.1333  28.9175   37.9475  27.1000
1196               580      0  23.6333   47.2267  24.8140   43.4720  26.1667
1202               590     20  21.2900   36.6333  19.3900   35.3633  23.5667
1323               680      0  20.2900   39.3333  19.6000   38.3600  20.5333
1334               590     20  21.1000   43.8267  20.6000   41.7000  21.8567
1514               690     20  21.3900   39.5900  20.8600   39.5600  23.0000
1733               770     20  20.2000   40.5000  19.2900   40.4333  20.5000
1835               720     10  22.2000   37.9333  21.1000   37.0000  23.1667
1912               610      0  19.8233   34.9667  19.1250   32.2225  20.3900
1964               620      0  22.7000   41.7233  22.4267   39.0000  23.2900

      unidade3
352    38.8633
427    36.0000
696    37.8333
744    39.1933
916    42.5967
993    41.9300
1173   34.8725
1182   42.4400
1196   40.5000
1202   34.5267
1323   40.3267
1334   47.7300
1514   37.1633
1733   39.1567
1835   36.6267
1912   34.3233
1964   39.2000

In [108]:
#Calcule a quantidade e o percentual de registros selecionados.

quantidade = len(df_acima_limite)
percentual = (quantidade / len(df6)) * 100

print("Quantidade de registros:", quantidade)
print("Percentual de registros:", round(percentual, 2), "%")

Quantidade de registros: 17
Percentual de registros: 0.86 %

In [111]:
#Calcule a corrente média da amostra.

df6["corrente"] = df6["eletrodomesticos"] / 220
corrente_media = df6["corrente"].mean()

In [115]:
#Crie um segundo DataFrame contendo simultaneamente potência ativa acima de 75% do máximo e corrente acima da média.
df_filtrado = df6[
    (df6["eletrodomesticos"] > limite) &
    (df6["corrente"] > corrente_media)
]

print(df_filtrado)

      eletrodomesticos  luzes    temp1  unidade1    temp2  unidade2    temp3  \
352                620      0  24.3900   44.3333  25.3700   37.7360  26.7300
427                650      0  20.8900   36.7000  18.2900   39.6633  21.2000
696                590     30  19.8567   47.6633  18.7000   34.1000  18.4267
744                740     20  19.5000   42.1333  18.2600   39.1967  19.8900
916                750     30  22.4300   43.0000  21.9267   40.1333  21.2300
993                690     10  22.5333   45.0267  22.0667   39.7900  22.3900
1173               580      0  21.6000   34.6267  19.5000   33.7600  22.5750
1182               600     20  24.8900   48.1333  28.9175   37.9475  27.1000
1196               580      0  23.6333   47.2267  24.8140   43.4720  26.1667
1202               590     20  21.2900   36.6333  19.3900   35.3633  23.5667
1323               680      0  20.2900   39.3333  19.6000   38.3600  20.5333
1334               590     20  21.1000   43.8267  20.6000   41.7000  21.8567
1514               690     20  21.3900   39.5900  20.8600   39.5600  23.0000
1733               770     20  20.2000   40.5000  19.2900   40.4333  20.5000
1835               720     10  22.2000   37.9333  21.1000   37.0000  23.1667
1912               610      0  19.8233   34.9667  19.1250   32.2225  20.3900
1964               620      0  22.7000   41.7233  22.4267   39.0000  23.2900

      unidade3  corrente
352    38.8633  2.818182
427    36.0000  2.954545
696    37.8333  2.681818
744    39.1933  3.363636
916    42.5967  3.409091
993    41.9300  3.136364
1173   34.8725  2.636364
1182   42.4400  2.727273
1196   40.5000  2.636364
1202   34.5267  2.681818
1323   40.3267  3.090909
1334   47.7300  2.681818
1514   37.1633  3.136364
1733   39.1567  3.500000
1835   36.6267  3.272727
1912   34.3233  2.772727
1964   39.2000  2.818182